# fly.toml app configuration file generated for blog-api-app on 2024-06-18T19:01:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-api-app'
primary_region = 'jnb'

[build]
  port = "3000"
  MONGODB_URI = "mongodb+srv://dewaldfourie0808:wwvjRvFy0pbdLxnc@cluster0.pcyohui.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
